### PR TITLE
Setup initial code - NMFL Project

### PR DESCRIPTION
**Pull request by akhilprathist-asu**
This is a basic layout template to get started with the project

### CODE REVIEW

**Review by Gautham-6 — DISMISSED** [review]
approved

**Review by Yashwanthdantanoor1 — APPROVED** [review]

**Comment by JanardhanReddy-Bommireddy** [comment]
Approved, can merge the PR

**Review by JanardhanReddy-Bommireddy — DISMISSED** [review]
Approved

**Review by Anila8707 — APPROVED** [review]
Working !!

**Pull request merged**
